WebTimeSheetManagement/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebTimeSheetManagement.Concrete;
using WebTimeSheetManagement.Filters;
using WebTimeSheetManagement.Interface;
using WebTimeSheetManagement.Models;
namespace WebTimeSheetManagement.Controllers
{
    [ValidateSuperAdminSession]
    public class ProjectController : Controller
    {
        IProject _IProject;
        public ProjectController()
        {
            _IProject = new ProjectConcrete();
        }

        // GET: Project
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        public JsonResult CheckProjectCodeExists(string ProjectCode)
        {
            try
            {
                var isProjectCodeExists = false;

                if (ProjectCode != null)
                {
                    isProjectCodeExists = _IProject.CheckProjectCodeExists(ProjectCode);
                }

                if (isProjectCodeExists)
                {
                    return Json(data: true);
                }
                else
                {
                    return Json(data: false);
                }
            }
            catch (Exception)
            {
                throw;
            }
        }

        public JsonResult CheckProjectNameExists(string ProjectName)
        {
            try
            {
                var isProjectNameExists = false;

                if (ProjectName != null)
                {
                    isProjectNameExists = _IProject.CheckProjectNameExists(ProjectName);
                }

                if (isProjectNameExists)
                {
                    return Json(data: true);
                }
                else
                {
                    return Json(data: false);
                } 
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(ProjectMaster ProjectMaster)
        {
            if (ModelState.IsValid)
            {
                var result = _IProject.SaveProject(ProjectMaster);

                if (result > 0)
                {
                    TempData["ProjectMessage"] = "Project Added Successfully";
                    ModelState.Clear();
                    return RedirectToAction("Add");
                }
            }

            return View(ProjectMaster);
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LoadProjectData()
        {
            try
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                int recordsTotal = 0;

                var projectdata = _IProject.ShowProjects(sortColumn, sortColumnDir, searchValue);
                recordsTotal = projectdata.Count();
                var data = projectdata.Skip(skip).Take(pageSize).ToList();

                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
            }
            catch (Exception)
            {
                throw;
            }

        }

        public JsonResult Delete(string ProjectID)
        {
            try
            {
                if (string.IsNullOrEmpty(Convert.ToString(ProjectID)))
                {
                    return Json("Error", JsonRequestBehavior.AllowGet);
                }

                var isExistsinTimesheet = _IProject.CheckProjectIDExistsInTimesheet(Convert.ToInt32(ProjectID));

                var isExistsinExpense = _IProject.CheckProjectIDExistsInExpense(Convert.ToInt32(ProjectID));

                if (isExistsinTimesheet == false && isExistsinExpense == false)
                {
                    var data = _IProject.ProjectDelete(Convert.ToInt32(ProjectID));

                    if (data > 0)
                    {
                        return Json(data: true, behavior: JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(data: false, behavior: JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    return Json(data: false, behavior: JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception)
            {
                throw;
            }
        }


    }
}

WebTimeSheetManagement/Views/Project/Add.cshtml
@model WebTimeSheetManagement.Models.ProjectMaster
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}

<h4 class="page-header">Add Project</h4>

<script>
    if ('@TempData["ProjectMessage"]' != '') {
        alert('@TempData["ProjectMessage"]');
    }
</script>

<div class="col-lg-6">
    @using (Html.BeginForm("Add", "Project", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="panel panel-default">
            <div class="panel-heading">Add Project Details</div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.LabelFor(model => model.ProjectCode, new { @class = "manadatory" })
                    @Html.TextBoxFor(model => model.ProjectCode, new { @class = "form-control", @maxlength = "90", @onblur = "CheckProjectCode();" })
                    @Html.ValidationMessageFor(model => model.ProjectCode, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ProjectName, new { @class = "manadatory" })
                    @Html.TextAreaFor(model => model.ProjectName, new { @class = "form-control", @maxlength = "90", @onblur = "CheckProjectName();" })
                    @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.NatureofIndustry, new { @class = "manadatory" })
                    @Html.TextAreaFor(model => model.NatureofIndustry, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.NatureofIndustry, "", new { @class = "text-danger" })
                </div>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-offset-0 col-md-12">
                            <input type="submit" onclick="return ValidateData();" value="Save Details" class="btn btn-success" />

                            @Html.ActionLink("Cancel", "Add", "Project", null, new { @class = "btn btn-danger" })

                            @Html.ActionLink("All Projects", "Index", "Project", null, new { @class = "btn btn-info" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<script type="text/javascript">

        function CheckProjectCode() {
            var url = '@Url.Content("~/")' + "Project/CheckProjectCodeExists";
            var source = "#ProjectCode";
            $.post(url, { ProjectCode: $(source).val() }, function (data) {
                if (data) {
                    $(source).val('');
                    alert("ProjectCode Already Used try unique one!");
                }
                else {

                }
            });
        }

        function CheckProjectName() {
            var url = '@Url.Content("~/")' + "Project/CheckProjectNameExists";
            var source = "#ProjectName";
            $.post(url, { ProjectName: $(source).val() }, function (data) {
                if (data) {
                    $(source).val('');
                    alert("ProjectName Already Used try unique one!");
                }
                else {

                }
            });
        }

</script>

WebTimeSheetManagement/Views/Project/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}



<link href="~/Scripts/dataTablesScripts/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="~/Scripts/dataTablesScripts/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/dataTablesScripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTablesScripts/dataTables.bootstrap4.min.js"></script>


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">All Expense</div>
            <div class="panel-body">
                <table id="myTable" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ProjectID</th>
                            <th>ProjectName</th>
                            <th>ProjectCode</th>
                            <th>NatureofIndustry</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                </table>

            </div>

            </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#myTable").DataTable({
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": true, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "ajax": {
                "url": "/Project/LoadProjectData",
                "type": "POST",
                "datatype": "json"
            },
            "columnDefs":
            [{
                "targets": [0],
                "visible": false,
                "searchable": false
            },
              {
                  "targets": [3],
                  "searchable": false,
                  "orderable": false
              },
              {
                  "targets": [4],
                  "searchable": false,
                  "orderable": false
              }


            ],
            "columns": [
                { "data": "ProjectID", "name": "ProjectID", "autoWidth": true },
                { "data": "ProjectName", "name": "ProjectName", "autoWidth": true },
                { "data": "ProjectCode", "name": "ProjectCode", "autoWidth": true },
                { "data": "NatureofIndustry", "title": "NatureofIndustry", "name": "NatureofIndustry", "autoWidth": true },

                 {
                     data: null, render: function (data, type, row) {

                         return "<a href='#' class='btn btn-danger' onclick=DeleteData('" + row.ProjectID + "'); >Delete</a>";


                     }
                 },



            ]

        });
    });
</script>



<script type="text/javascript">

    function DeleteData(ID) {
        if (confirm("Are you sure you want to delete ...?")) {
            DeleteSheet(ID);
        }
        else {
            return false;
        }
    }
    function DeleteSheet(ID) {
        var url = '@Url.Content("~/")' + "Project/Delete";
        $.post(url, { ProjectID: ID }, function (data) {
            if (data) {
                oTable = $('#myTable').DataTable();
                oTable.draw();
            }
            else {
                alert("This Project cannot be deleted it is already in use!");
            }
        });
    }
</script>